-- 알림 발송 이력 테이블 생성
-- 관리자가 FCM을 통해 발송한 알림의 기록을 저장합니다.

CREATE TABLE IF NOT EXISTS NOTIFICATION_TBL (
    NOTIFICATION_IDX BIGINT NOT NULL AUTO_INCREMENT COMMENT '알림 고유 ID',
    TITLE VARCHAR(200) NOT NULL COMMENT '알림 제목',
    BODY TEXT NOT NULL COMMENT '알림 내용',
    FILTER_CRITERIA TEXT COMMENT '필터 조건 (JSON)',
    TARGET_COUNT INT COMMENT '대상자 수',
    SUCCESS_COUNT INT COMMENT '발송 성공 수',
    FAILURE_COUNT INT COMMENT '발송 실패 수',
    SENT_AT DATETIME COMMENT '발송 완료 시각',
    CREATED_BY VARCHAR(200) COMMENT '발송 관리자 ID (이메일)',
    CREATED_AT DATETIME NOT NULL COMMENT '생성 시각',

    PRIMARY KEY (NOTIFICATION_IDX),
    INDEX idx_sent_at (SENT_AT DESC),
    INDEX idx_created_by (CREATED_BY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='알림 발송 이력';
